#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.9
apt-get -y update
apt-get install -y haproxy=2.9.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 199047-web-01 34.234.201.134:80 check
   server 199047-web-02 34.229.69.154:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start